# A YAML binding matching the node

compatible: "nabucasa,esphome"
description: "Enable support of esphome"

include: [base.yaml]

properties:
    "#address-cells":
      type: int
      required: false
      default: 1
      const: 1
    "#size-cells":
      type: int
      required: false
      default: 0
      const: 0
    entity_id:
      type: string
      required: true
      description: Home assistant entity id to use for this device.
    friendly_name:
      type: string
      required: false
      description: Friendly name for this device.
    password:
      type: string
      required: true
      description: password required to connect to device.
    area:
      type: string
      required: false
      default: unknown
      description: The area where the device is located.
    port:
      type: int
      required: false
      default: 6053
      description: The port to run the API Server on.
